# Generated by Django 5.2.1 on 2025-05-09 20:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('category', models.CharField(max_length=100, verbose_name='Категорія')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кількість')),
                ('unit', models.CharField(max_length=50, verbose_name='Одиниця виміру')),
                ('status', models.CharField(choices=[('available', 'Доступний'), ('reserved', 'Зарезервований'), ('depleted', 'Вичерпаний')], default='available', max_length=20, verbose_name='Статус')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата додавання')),
                ('added_by', models.CharField(max_length=100, verbose_name='Хто додав')),
                ('organization', models.CharField(max_length=255, verbose_name='Організація')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Термін придатності')),
                ('storage_location', models.CharField(max_length=255, verbose_name='Місце зберігання')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурси',
            },
        ),
    ]
