# Generated by Django 5.2.1 on 2025-05-11 09:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='По Батькові')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram ID')),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата реєстрації')),
                ('status', models.CharField(choices=[('active', 'Активний'), ('inactive', 'Неактивний'), ('pending', 'Очікує підтвердження'), ('blocked', 'Заблокований')], default='pending', max_length=20, verbose_name='Статус')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Навички')),
                ('organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Організація')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='volunteer_photos/', verbose_name='Фото')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Останній вхід')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Волонтер',
                'verbose_name_plural': 'Волонтери',
            },
        ),
    ]
