# Generated by Django 5.2.1 on 2025-05-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
    ]
