# Generated by Django 5.2.1 on 2025-05-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_volunteer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='resource_photos/', verbose_name='Фото'),
        ),
    ]
