# Generated by Django 5.2.1 on 2025-05-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_resource_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('медичні засоби', 'Медичні засоби'), ('спорядження', 'Спорядження'), ('продукти', 'Продукти'), ('обладнання', 'Обладнання'), ('одяг', 'Одяг'), ('інше', 'Інше')], default='інше', max_length=100, verbose_name='Категорія'),
        ),
    ]
