# Generated by Django 5.2.1 on 2025-05-11 10:40

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_resource_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('медичні засоби', 'Медичні засоби'), ('спорядження', 'Спорядження'), ('продукти', 'Продукти'), ('обладнання', 'Обладнання'), ('одяг', 'Одяг'), ('інше', 'Інше')], db_index=True, default='інше', max_length=100, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='date_added',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата додавання'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Термін придатності'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='organization',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Організація'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('available', 'Доступний'), ('reserved', 'Зарезервований'), ('depleted', 'Вичерпаний')], db_index=True, default='available', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='storage_location',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Місце зберігання'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(db_index=True, max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_login',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Останній вхід'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='organization',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Організація'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='registration_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='status',
            field=models.CharField(choices=[('active', 'Активний'), ('inactive', 'Неактивний'), ('pending', 'Очікує підтвердження'), ('blocked', 'Заблокований')], db_index=True, default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['name'], name='api_resourc_name_bcf975_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['category'], name='api_resourc_categor_7f2acc_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['status'], name='api_resourc_status_1a931d_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['date_added'], name='api_resourc_date_ad_0fcf70_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['organization'], name='api_resourc_organiz_21692d_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['storage_location'], name='api_resourc_storage_074735_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteer',
            index=models.Index(fields=['last_name', 'first_name'], name='api_volunte_last_na_8994b2_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteer',
            index=models.Index(fields=['email'], name='api_volunte_email_97788a_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteer',
            index=models.Index(fields=['status'], name='api_volunte_status_5a7d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteer',
            index=models.Index(fields=['registration_date'], name='api_volunte_registr_6fa239_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteer',
            index=models.Index(fields=['organization'], name='api_volunte_organiz_f1c504_idx'),
        ),
    ]
