# Generated by Django 5.2.1 on 2025-05-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_resource_category_alter_resource_date_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('added', 'Додано'), ('updated', 'Змінено'), ('deleted', 'Видалено')], max_length=10, verbose_name='Дія')),
                ('subject', models.CharField(choices=[('resource', 'Ресурс'), ('volunteer', 'Волонтер')], max_length=20, verbose_name='Предмет')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час дії')),
            ],
            options={
                'verbose_name': 'Журнал дій',
                'verbose_name_plural': 'Журнал дій',
            },
        ),
    ]
