# Generated by Django 5.2.1 on 2025-05-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_actionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис дії'),
        ),
    ]
