# Generated by Django 5.2.1 on 2025-06-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_actionlog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='performer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Виконавець'),
        ),
    ]
